<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>golo</string>
	</array>
	<key>name</key>
	<string>Golo</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>comment</key>
			<string>comment with #</string>
			<key>match</key>
			<string>(#).*$
?</string>
			<key>name</key>
			<string>comment.line.number-sign.golo</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"""</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.golo</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"""</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.golo</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.third.golo</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(\$\w+|\$\{[^\}]+\})</string>
					<key>name</key>
					<string>variable.parameter.template.golo</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.golo</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.golo</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.golo</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.golo</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(\$\w+|\$\{[^\}]+\})</string>
					<key>name</key>
					<string>variable.parameter.template.golo</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.golo</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.golo</string>
				</dict>
			</dict>
			<key>end</key>
			<string>'</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.golo</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.single.golo</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.golo</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>`</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.golo</string>
				</dict>
			</dict>
			<key>end</key>
			<string>`</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.golo</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.single.golo</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(true|false|null|super)\b</string>
			<key>name</key>
			<string>constant.language.golo</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b((0(x|X)[0-9a-fA-F]*)|(([0-9]+\.?[0-9]*)|(\.[0-9]+))((e|E)(\+|-)?[0-9]+)?)([LlFfUuDd]|UL|ul)?\b</string>
			<key>name</key>
			<string>constant.numeric.golo</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b([A-Z][A-Z0-9_]+)\b</string>
			<key>name</key>
			<string>constant.other.golo</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(this)\b</string>
			<key>name</key>
			<string>constant.other.golo</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(var|let|val|define|mixin|get|put|undefine|copy|freeze|local)\b</string>
			<key>name</key>
			<string>storage.modifier.golo</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(try|catch|finally|throw)\b</string>
			<key>name</key>
			<string>keyword.control.catch-exception.golo</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(if|then|else|match|while|for|foreach|do|return|when|otherwise|where|break|continue)\b</string>
			<key>name</key>
			<string>keyword.control.golo</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(println|function|pimp|augment|class|DynamicObject|module|import)\b</string>
			<key>name</key>
			<string>keyword.other.golo</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(in|not|and|or|is|isnt|as|assert)\b</string>
			<key>name</key>
			<string>keyword.operator.golo</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(==|!=|&lt;=|&gt;=|&lt;&gt;|&lt;|&gt;)</string>
			<key>name</key>
			<string>keyword.operator.comparison.golo</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(=)</string>
			<key>name</key>
			<string>keyword.operator.assignment.golo</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(:|\||)</string>
			<key>name</key>
			<string>keyword.operator.declaration.golo</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\.)</string>
			<key>name</key>
			<string>keyword.operator.dot.golo</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\-\-|\+\+)</string>
			<key>name</key>
			<string>keyword.operator.increment-decrement.golo</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\-|\+|\*|\/|%)</string>
			<key>name</key>
			<string>keyword.operator.arithmetic.golo</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(!|&amp;&amp;|\|\|)</string>
			<key>name</key>
			<string>keyword.operator.logical.golo</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(;)</string>
			<key>name</key>
			<string>punctuation.terminator.golo</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(range)|\(|\)|\b</string>
			<key>name</key>
			<string>storage.type.buildin.golo</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(Array|alength|aget|aset)\b</string>
			<key>name</key>
			<string>storage.type.buildin.array.golo</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.golo</string>
	<key>uuid</key>
	<string>1cc2b523-9678-42fe-80ae-2604ff57e138</string>
</dict>
</plist>
